### ISSUE TITLE
Build fails with "-z unexpected at this time" on Windows

### ISSUE THREAD

**Issue by robojeb** [alexcrichton/libz-sys#13]
I am trying to build the git2 crate and one of its dependencies is libz-sys.

When it builds it fails during the install step with the error "-z unexpected at this time"

```
process didn't exit successfully: `C:\Users\roboj\Documents\GitHub\kessler\target\debug\build\libz-sys-3b80a22c8da6c40e\build-script-build` (exit code: 101)
--- stdout
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("i686-pc-windows-gnu")
debug=true opt-level=0
HOST = Some("i686-pc-windows-gnu")
TARGET = Some("i686-pc-windows-gnu")
TARGET = Some("i686-pc-windows-gnu")
HOST = Some("i686-pc-windows-gnu")
CC_i686-pc-windows-gnu = None
CC_i686_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("i686-pc-windows-gnu")
HOST = Some("i686-pc-windows-gnu")
CFLAGS_i686-pc-windows-gnu = None
CFLAGS_i686_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
running: "make" "-f" "win32/Makefile.gcc" "install" "prefix=C:\\Users\\roboj\\Documents\\GitHub\\kessler\\target\\debug\\build\\libz-sys-f39c483ea4a3ee4b\\out" "INCLUDE_PATH=C:\\Users\\roboj\\Documents\\GitHub\\kessler\\target\\debug\\build\\libz-sys-f39c483ea4a3
ee4b\\out\\include" "LIBRARY_PATH=C:\\Users\\roboj\\Documents\\GitHub\\kessler\\target\\debug\\build\\libz-sys-f39c483ea4a3ee4b\\out\\lib" "BINARY_PATH=C:\\Users\\roboj\\Documents\\GitHub\\kessler\\target\\debug\\build\\libz-sys-f39c483ea4a3ee4b\\out\\bin"
win32/Makefile.gcc:128: recipe for target 'install' failed

--- stderr
-z was unexpected at this time.
make: *** [install] Error 255
thread 'main' panicked at 'failed to run successfully: exit code: 2', C:\Users\roboj\.cargo\registry\src\github.com-1ecc6299db9ec823\libz-sys-1.0.10\build.rs:189
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I have `cmake` and `make` and `gcc` installed.

**Comment by alexcrichton** [comment]
Odd! @robojeb what version of `make` do you have installed? (is this an msys2 one?)

**Comment by robojeb** [comment]
@alexcrichton no, I installed MinGW. I totally forgot Msys2 exists. I will go try that as well.
Just for reference the version installed by MinGW is

```
GNU Make 3.82.90
Built for i686-pc-mingw32
Copyright (C) 1988-2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by robojeb** [comment]
Switching to Msys2 solved the make problem but introduces a compilation problem.

I presume I am missing some library (though it appears to be the standard library)

```
--- stderr
gzlib.c: In function ‘gz_open’:
gzlib.c:14:17: warning: implicit declaration of function ‘lseek’ [-Wimplicit-function-declaration]
 #  define LSEEK lseek
                 ^
gzlib.c:256:24: note: in expansion of macro ‘LSEEK’
         state->start = LSEEK(state->fd, 0, SEEK_CUR);
                        ^
gzread.c: In function ‘gz_load’:
gzread.c:30:15: warning: implicit declaration of function ‘read’ [-Wimplicit-function-declaration]
         ret = read(state->fd, buf + *have, len - *have);
               ^
gzread.c: In function ‘gzclose_r’:
gzread.c:591:11: warning: implicit declaration of function ‘close’ [-Wimplicit-function-declaration]
     ret = close(state->fd);
           ^
gzwrite.c: In function ‘gz_comp’:
gzwrite.c:84:15: warning: implicit declaration of function ‘write’ [-Wimplicit-function-declaration]
         got = write(state->fd, strm->next_in, strm->avail_in);
               ^
gzwrite.c: In function ‘gzclose_w’:
gzwrite.c:573:9: warning: implicit declaration of function ‘close’ [-Wimplicit-function-declaration]
     if (close(state->fd) == -1)
         ^
Cannot export gzopen_w: symbol not defined
collect2: error: ld returned 1 exit status
make: *** [win32/Makefile.gcc:96: zlib1.dll] Error 1
```

I don't know if it causes any problems to use the version of cargo on the default windows path rather than explicitly installing rustup inside Msys2.

**Comment by alexcrichton** [comment]
Hm it looks like compilers are getting mixed up or something like that? If functions like `close` don't exist that seems like a serious problem!

**Comment by robojeb** [comment]
The implicit declarations are just warnings, though ominous. I can actually quell them by injecting `#include <unistd.h>`

The biggest issue is that it seems that `gzopen_w` is not being built. 
I have tried building in msys64, msys32, cmd, and powershell. 
I even tried re-running the `configure` script in the cargo registry, and doing a clean build.
My thinking was that it was related to a define not being set correctly in some build configurations.

This seems to be more likely to be a problem zlib building on windows.

**Comment by robojeb** [comment]
I managed to get this to build (though now I have errors with libssh2-sys, but I think I will give up and go to linux for now).

For reference to fix the issue I referenced [https://github.com/madler/zlib/issues/45](this issue).
Adding `|| defined __CYGWIN__` right before the definition of the function `gzopen_w` in `gzlib.c` will allow the build to proceed.

@alexcrichton it looks like the version you chose to vendor doesn't have this fix, the latest version in git repos has moved to a slightly different method of solving the same problem.

**Comment by robojeb** [comment]
Please ignore me while I sit here and blather to myself. 
I ran a cargo update and it pulled 1.0.12 which compiles fine apparently.

**Comment by alexcrichton** [comment]
@robojeb glad it got worked out!

**Comment by johnsheleg** [comment]
Is there a solution to this problem besides using Msys2?
