### ISSUE TITLE
Inflate fails with error code -2 on zlib 1.2.11

### ISSUE THREAD

**Issue by shssoichiro** [alexcrichton/libz-sys#15]
I have a library that calls into libz-sys as such:

```
pub struct Stream<D: Direction> {
    raw: libz_sys::z_stream,
    _marker: marker::PhantomData<D>,
}

impl Stream<Decompress> {
    pub fn decompress_vec(&mut self, input: &mut [u8], output: &mut Vec<u8>) -> c_int {
        self.raw.avail_in = (input.len() - self.total_in()) as c_uint;
        self.raw.avail_out = (output.capacity() - self.total_out()) as c_uint;

        unsafe {
            self.raw.next_in = input.as_mut_ptr().offset(self.total_in() as isize);
            self.raw.next_out = output.as_mut_ptr().offset(self.total_out() as isize);
            let rc = libz_sys::inflate(&mut self.raw, libz_sys::Z_NO_FLUSH);
            output.set_len(self.total_out() as usize);
            rc
        }
    }
}
```

This code, to the best of my knowledge, worked on zlib 1.2.10 (I no longer have easy access to 1.2.10 to test with, but this definitely worked on 1.2.8), but fails on Linux using zlib 1.2.11, with "Error code on decompress: -2", on the line calling `libz_sys::inflate`. Could there have been a breaking change between the zlib versions that is causing this failure? (See: https://github.com/shssoichiro/oxipng/issues/54)

**Comment by alexcrichton** [comment]
Hm maybe? I'm not too familiar with the internals of zlib unfortunately :(

**Comment by shssoichiro** [comment]
Unfortunately I was unable to determine if this was a bug in this crate, and have switched my crate to miniz-sys as a workaround. I'll close this for now, and if it becomes determined that this is a bug in this crate, it can be reopened.
