### ISSUE TITLE
build for target=arm...musl fails

### ISSUE THREAD

**Issue by rainboh** [alexcrichton/libz-sys#35]
I tried to x-compile on a x86_64 linux system

~~~
cargo build --target=arm-unknown-linux-musleabihf
cargo build --target=arm-unknown-linux-musleabi
cargo build --target=armv7-unknown-linux-musleabihf
~~~

all are failing with error "Compiler error reporting is too harsh for ./configure (perhaps remove -Werror)", e.g.

~~~
   Compiling libz-sys v1.0.18 (https://github.com/alexcrichton/libz-sys.git#8eb6f9e8)
error: failed to run custom build command for `libz-sys v1.0.18 (https://github.com/alexcrichton/libz-sys.git#8eb6f9e8)`
process didn't exit successfully: `/home/rainer/test/rust/lg2/lg2_test/target/debug/build/libz-sys-79688570e7235f69/build-script-build` (exit code: 1)
--- stdout
cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
cargo:rerun-if-changed=build.rs
OPT_LEVEL = Some("0")
TARGET = Some("arm-unknown-linux-musleabihf")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("arm-unknown-linux-musleabihf")
TARGET = Some("arm-unknown-linux-musleabihf")
HOST = Some("x86_64-unknown-linux-gnu")
CC_arm-unknown-linux-musleabihf = None
CC_arm_unknown_linux_musleabihf = None
TARGET_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
CROSS_COMPILE = None
TARGET = Some("arm-unknown-linux-musleabihf")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_arm-unknown-linux-musleabihf = None
CFLAGS_arm_unknown_linux_musleabihf = None
TARGET_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "./configure" "--prefix=/home/rainer/test/rust/lg2/lg2_test/target/arm-unknown-linux-musleabihf/debug/build/libz-sys-a4825891e6086beb/out"
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.


command did not execute successfully, got: exit code: 1
~~~

Some additonal setup or parameters are needed for cross-compiling ?

**Comment by rainboh** [comment]
configure.log reports
~~~
./configure: 182: ./configure: arm-linux-musleabihf-gcc: not found
~~~

Now I tried compiling with
~~~
1) CC=arm-linux-gnueabihf-gcc cargo build --target=arm-unknown-linux-musleabihf
2) CC=arm-linux-gnueabihf-cpp cargo build --target=arm-unknown-linux-musleabihf
3) CC=arm-linux-gnueabihf-g++ cargo build --target=arm-unknown-linux-musleabihf
~~~
1) does succeed.
2) reports in configure.log
~~~
arm-linux-gnueabi-cpp: fatal error: ‘-c’ is not a valid option to the preprocessor
~~~
3) outputs a bunch of compile errors on console


Is 1) a proper solution to compile the crate  ? (I thought 'cargo build target=...' is sufficient )
Or do I need to get "arm-linux-musleabihf-gcc" ? If yes where can I get it ? (I'm on Ubuntu 17.10)

**Comment by rainboh** [comment]
Ok. My expectation was same as expresssed here https://github.com/rust-lang/cargo/issues/4741#issuecomment-349750036

From discussion there I can see, currently it is still necessary to pass via environment variables proper information about compiler, include path, library path ... beside cargo's 'target=...' option

So either "CC=arm-linux-gnueabihf-gcc" or "CROSS_COMPILE="arm-linux-gnueabihf-" are good to pick proper cross-compiler.

I assume "CROSS_COMPILE=..." should be preferred ?

And in case wrong header files are used I can fix it by using "CFLAGS=I..." (faced that issue here https://github.com/tailhook/vagga/pull/482#issuecomment-354473114)

Before closing this thread it would be nice if someone can confirm if my understanding is correct now or point out where I'm still wrong.
Thanks.

**Comment by alexcrichton** [comment]
Hello and thanks for the report! Looks like you've found what's up though in the sense that it looks like you needed to configure the C compiler for the cross-compilation. I'd recommend using [`CC_$target`](https://github.com/alexcrichton/cc-rs#external-configuration-via-environment-variables) personally.

**Comment by rainboh** [comment]
Thanks for your confirmation.
