### ISSUE TITLE
Yank all broken versions from crates.io

### ISSUE THREAD

**Issue by klausi** [alexcrichton/libz-sys#36]
https://crates.io/crates/libz-sys contains quite a few versions that do not compile with recent Rust versions, they should be yanked.

* 0.0.1:
```
error: expected identifier, found `"pkg-config"`
 --> /home/klausi/.cargo/registry/src/github.com-1ecc6299db9ec823/libz-sys-0.0.1/src/build.rs:1:14
  |
1 | extern crate "pkg-config" as pkg_config;
  |              ^^^^^^^^^^^^ expected identifier

error: aborting due to previous error

error: Could not compile `libz-sys`.
```
* 0.1.0

0.1.1 does not compile because pkg-config v0.3.0 does not compile, so we probably also need to yank broken versions there.

**Comment by alexcrichton** [comment]
Thanks for the report! I [commented over on the Cargo PR](https://github.com/rust-lang/cargo/pull/5275#issuecomment-377965911) though in that I don't think this is quite the right solution, so I'm going to close this.
