### ISSUE TITLE
Regression building iOS targets between 1.0.20 --> 1.0.21+

### ISSUE THREAD

**Issue by tiras-j** [alexcrichton/libz-sys#44]
Looking at the commits I'm guessing this has something to do with the rework to use `cc` crate for building libz, but for the life of me I can't figure out why.

Targets I'm building for (and results on 1.0.21, which are the same afaict to master branch):
- `aarch64-apple-ios` fails trying to resolve snprintf of all things [see gist output](https://gist.github.com/tiras-j/2bbc0dd1c57f7f54a657dcfa52244a81)
- `armv7-apple-ios` gives warnings but no [failure](https://gist.github.com/tiras-j/a9f56a8cf333820c4dfd85f122d0355a)
- `armv7s-apple-ios` has the same [warnings](https://gist.github.com/tiras-j/e222e7310e87ab8c85d3faf160f452f6)

What's crazy to me is I've looked at the libraries in those sysroot paths and libc.tbd absolutely contains `_snprintf` and the other symbols (I mean... no surprise there). Furthermore writing an incredibly simple c program that uses stdio + snprintf etc and compiling with the identical cross-compilation arguments (less the -D options since I'm not using them, but then again perhaps those are influencing the compilation somehow?) compiles just fine (at least for `aarch64-apple-ios`). 

Any thoughts on what could be going on here?

**Comment by tiras-j** [comment]
Well speaking of checking into the #define options to the compiler... looks like `-D_POSIX_SOURCE` is the problem [somehow](https://gist.github.com/tiras-j/ad7e54c50bee4beb3a01804259e4cd74).

I'll look into that a bit and see if I can come up with anything.

**Comment by alexcrichton** [comment]
Ah sorry for the breakage! That seems like a reasonable fix to me as well, want to send a PR to do that on ios?
