### ISSUE TITLE
"error: no packages found with binaries or examples" when install

### ISSUE THREAD

**Issue by Arthur111** [alexcrichton/libz-sys#47]
I downloaded the project and build it (cargo build --release) and its ok. ("Finished release [optimized] target(s) in 8.21s")
But when i try to install it with : cargo install , i got the message "error: no packages found with binaries or examples"

How can i resolve that , thank you

**Comment by alexcrichton** [comment]
Thanks for the report! There's no need, however, to run `cargo install` for this crate. You don't need to `cargo install` crates to use them, they can simply be added to `Cargo.toml` for projects and Cargo will automatically download and build them!
